"""add upload model

Revision ID: 408633f7b277
Revises: init
Create Date: 2026-09-18 15:42:14.620421

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "408633f7b277"
down_revision: Union[str, None] = "init"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uploads",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("original_filename", sa.String(), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("share_token", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("max_downloads", sa.Integer(), nullable=True),
        sa.Column("download_count", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "EXPIRED",
                "DOWNLOAD_LIMIT_REACHED",
                "DELETED",
                name="uploadstatus",
            ),
            nullable=False,
        ),
        sa.Column("management_token_hash", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_uploads_expires_at"), "uploads", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_uploads_id"), "uploads", ["id"], unique=False)
    op.create_index(
        op.f("ix_uploads_share_token"), "uploads", ["share_token"], unique=True
    )
    op.create_index(op.f("ix_uploads_status"), "uploads", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_uploads_status"), table_name="uploads")
    op.drop_index(op.f("ix_uploads_share_token"), table_name="uploads")
    op.drop_index(op.f("ix_uploads_id"), table_name="uploads")
    op.drop_index(op.f("ix_uploads_expires_at"), table_name="uploads")
    op.drop_table("uploads")
    # ### end Alembic commands ###
